---
abstract: 'A Semantic Web Framework'
author:
  - 'Gregory Todd Williams  C<< <gwilliams@cpan.org> >>'
  - 'Gregory Todd Williams <gwilliams@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::Exception: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.12'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Attean
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Data::UUID: 0
  DateTime::Format::W3CDTF: 0
  Digest::SHA: 0
  Encode: 0
  I18N::LangTags: 0
  IRI: 0.004
  List::Util: 0
  Moo: 1.006
  RDF::Query: 2.91
  Scalar::Util: 0
  Set::Scalar: 0
  Sub::Install: 0
  Sub::Name: 0
  Try::Tiny: 0
  Type::Tiny: 0
  URI::Escape: 1.36
  URI::Namespace: 0
  namespace::clean: 0
  perl: 5.14.0
resources:
  IRC: irc://irc.perl.org/#perlrdf
  bugtracker: https://github.com/kasei/attean/issues
  homepage: http://search.cpan.org/dist/Attean/
  license: http://dev.perl.org/licenses/
  repository: http://github.com/kasei/attean/
version: 0.000_01
